apiVersion: v1
kind: Service
metadata:
  name: studentapp-mariadb
  labels:
    app: studentapp
spec:
  ports:
    - port: 3306
  selector:
    app: studentapp
    tier:  mariadb
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: studentapp-mariadb
  labels:
    app: studentapp
spec:
  selector:
    matchLabels:
      app: studentapp
      tier:  mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: studentapp
        tier:  mariadb
    spec:
      containers:
      - image:  mariadb
        name:  studentapp-mariadb
        env:
        - name: Tomcat__SERVICE_HOST
          value: "studentapp-tomcat"
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: studentapp
        - name: MYSQL_USER
          value: student
        - name: MYSQL_PASSWORD
          value: student
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-init
          mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mariadb-init
          persistentVolumeClaim:
            claimName: studentapp-initdb-pv-claim
