apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: studentapp-tomcat
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: studentapp-tomcat
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: studentapp-tomcat
        tier: frontend
        track: stable
    spec:
      containers:
      - name: nginx
        image: satish736/studentapp-frontend:3.0
        volumeMounts:
        - name: reverse-proxy
          mountPath: /etc/nginx/conf.d/
      volumes:
      - name: reverse-proxy
        configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
          name: conf-nginx
