kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: studentapp-initdb-pv-claim
  labels:
    app: studentapp
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
