---
apiVersion: v1
kind: Pod
metadata:
 name: satishtrainings
 labels:
   app: studentapp
spec:
 containers:
    - name: front-end
      image: nginx
      ports:
        - containerPort: 80
    - name: backend
      image: nickchase/rss-php-nginx:v1
      ports:
        - containerPort: 88
